project:
  type: website

website:
  title: "My Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ArushiKumar11

  page-navigation: true
  sidebar:
    style: floating
    contents:
      - index.qmd
      - about.qmd
      - section: "Posts"
        contents: posts/*

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
